export const appConstants = {
  SET_SHOWSPLASH: 'SET_SHOWSPLASH',
  SET_FIRSTLOAD: 'SET_FIRSTLOAD',
  SET_LOADINGFULLSCREEN: 'SET_LOADINGFULLSCREEN',
  SET_SHOWWELCOME: 'SET_SHOWWELCOME',
};

export const authConstants = {
  SET_USER: 'SET_USER',
};

export const fairsConstants = {
  SET_FAIRSLIST: 'SET_FAIRSLIST',
  SET_FAIRSUPCOMING: 'SET_FAIRSUPCOMING',
};

export const standsConstants = {
  SET_STANDSLIST: 'SET_STANDSLIST',
  SET_STANDSBESTS: 'SET_STANDSBESTS',
};

export const mapsConstants = {
  SET_MAPSCURRENTPOSITION: 'SET_MAPSCURRENTPOSITION',
  SET_MAPSLOCATIONAVAILABLE: 'SET_MAPSLOCATIONAVAILABLE',
};
