export enum ERoutesName {
  ROOT = "/",
  APP = "/app",
  PRODUCTS_LIST = "/app/productos",
  FAVORITES_LIST = "/app/favoritos",
  MY_SANBLE = "/app/misanble",
  NEAR_YOU = "/app/cerca",
  PROFILE = "/app/perfil",
  FAIRS_LIST = "/app/ferias",
  FAIR_DETAILS = "/app/ferias/:fairID",
  FAIR_DETAILS_MAP = "/app/ferias/:fairID/mapa",
  FAIR_DETAILS_PHOTO = "/app/ferias/:fairID/foto/:photoID",
  FAIR_DETAILS_PHOTO_SLIDES = "/app/ferias/:fairID/fotos",
  FAIR_DETAILS_PHOTO_NEW = "/app/ferias/:fairID/foto",
  STANDS_LIST = "/app/stands",
  STAND_DETAILS = "/app/stands/:standID",
  SESSION = "/app/sesion",
  SESSION_SIGNIN = "/app/sesion/entrar",
  SESSION_SIGNUP = "/app/sesion/registrarse",
}
