export const appConstants = {
  SET_SHOW_SIDEBAR: "SET_SHOW_SIDEBAR",
  SET_OPEN_NOTIFICATIONS: "SET_OPEN_NOTIFICATIONS",
  SET_READY_TO_USE: "SET_READY_TO_USE",
  SET_SCROLL_TOP: "SET_SCROLL_TOP",
  SET_IS_LOADING_FULL: "SET_IS_LOADING_FULL",
  SET_HIDE_MOBILE_WELCOME: "SET_HIDE_MOBILE_WELCOME",
};

export const authConstants = {
  SET_USER: "SET_USER",
};
