export const appConstants = {
  SHOW_SIDEBAR: "SHOW_SIDEBAR",
  OPEN_NOTIFICATIONS: "OPEN_NOTIFICATIONS",
  SET_READY_TO_USE: "SET_READY_TO_USE",
  SET_SCROLL_TOP: "SET_SCROLL_TOP",
  SET_IS_LOADING_FULL: "SET_IS_LOADING_FULL",
};

export const authConstants = {
  SET_USER: "SET_USER",
};
